import * as schema from "@/db/schema";

import {
  createSelectSchema,
  createInsertSchema,
  createUpdateSchema,
} from "drizzle-typebox";

export const schemas = {
  select: {
    statuses: createSelectSchema(schema.statuses),
    locationTypes: createSelectSchema(schema.locationTypes),
    locations: createSelectSchema(schema.locations),
    characterAliases: createSelectSchema(schema.characterAliases),
    speciesAliases: createSelectSchema(schema.speciesAliases),
    species: createSelectSchema(schema.species),
    maps: createSelectSchema(schema.maps),
    relativeTypes: createSelectSchema(schema.relativeTypes),
    relatives: createSelectSchema(schema.relatives),
    contracts: createSelectSchema(schema.contracts),
    characters: createSelectSchema(schema.characters),
    characterAffiliations: createSelectSchema(schema.characterAffiliations),
    affiliations: createSelectSchema(schema.affiliations),
    characterOccupations: createSelectSchema(schema.characterOccupations),
    occupations: createSelectSchema(schema.occupations),
  },
  insert: {
    statuses: createInsertSchema(schema.statuses),
    locationTypes: createInsertSchema(schema.locationTypes),
    locations: createInsertSchema(schema.locations),
    characterAliases: createInsertSchema(schema.characterAliases),
    speciesAliases: createInsertSchema(schema.speciesAliases),
    species: createInsertSchema(schema.species),
    maps: createInsertSchema(schema.maps),
    relativeTypes: createInsertSchema(schema.relativeTypes),
    relatives: createInsertSchema(schema.relatives),
    contracts: createInsertSchema(schema.contracts),
    characters: createInsertSchema(schema.characters),
    characterAffiliations: createInsertSchema(schema.characterAffiliations),
    affiliations: createInsertSchema(schema.affiliations),
    characterOccupations: createInsertSchema(schema.characterOccupations),
    occupations: createInsertSchema(schema.occupations),
  },
  update: {
    statuses: createUpdateSchema(schema.statuses),
    locationTypes: createUpdateSchema(schema.locationTypes),
    locations: createUpdateSchema(schema.locations),
    characterAliases: createUpdateSchema(schema.characterAliases),
    speciesAliases: createUpdateSchema(schema.speciesAliases),
    species: createUpdateSchema(schema.species),
    maps: createUpdateSchema(schema.maps),
    relativeTypes: createUpdateSchema(schema.relativeTypes),
    relatives: createUpdateSchema(schema.relatives),
    contracts: createUpdateSchema(schema.contracts),
    characters: createUpdateSchema(schema.characters),
    characterAffiliations: createUpdateSchema(schema.characterAffiliations),
    affiliations: createUpdateSchema(schema.affiliations),
    characterOccupations: createUpdateSchema(schema.characterOccupations),
    occupations: createUpdateSchema(schema.occupations),
  },
};
