import * as schema from "@/db/schema";

import {
  createSelectSchema,
  createInsertSchema,
  createUpdateSchema,
} from "drizzle-zod";

export const schemas = {
  select: {
    status: createSelectSchema(schema.statuses),
    locationType: createSelectSchema(schema.locationTypes),
    location: createSelectSchema(schema.locations),
    characterAlias: createSelectSchema(schema.characterAliases),
    speciesAlias: createSelectSchema(schema.speciesAliases),
    species: createSelectSchema(schema.species),
    map: createSelectSchema(schema.maps),
    relativeType: createSelectSchema(schema.relativeTypes),
    relative: createSelectSchema(schema.relatives),
    contract: createSelectSchema(schema.contracts),
    character: createSelectSchema(schema.characters),
    characterAffiliation: createSelectSchema(schema.characterAffiliations),
    affiliation: createSelectSchema(schema.affiliations),
    characterOccupation: createSelectSchema(schema.characterOccupations),
    occupation: createSelectSchema(schema.occupations),
  },
  insert: {
    status: createInsertSchema(schema.statuses),
    locationType: createInsertSchema(schema.locationTypes),
    location: createInsertSchema(schema.locations),
    characterAlias: createInsertSchema(schema.characterAliases),
    speciesAlias: createInsertSchema(schema.speciesAliases),
    species: createInsertSchema(schema.species),
    map: createInsertSchema(schema.maps),
    relativeType: createInsertSchema(schema.relativeTypes),
    relative: createInsertSchema(schema.relatives),
    contract: createInsertSchema(schema.contracts),
    character: createInsertSchema(schema.characters),
    characterAffiliation: createInsertSchema(schema.characterAffiliations),
    affiliation: createInsertSchema(schema.affiliations),
    characterOccupation: createInsertSchema(schema.characterOccupations),
    occupation: createInsertSchema(schema.occupations),
  },
  update: {
    status: createUpdateSchema(schema.statuses),
    locationType: createUpdateSchema(schema.locationTypes),
    location: createUpdateSchema(schema.locations),
    characterAlias: createUpdateSchema(schema.characterAliases),
    speciesAlias: createUpdateSchema(schema.speciesAliases),
    species: createUpdateSchema(schema.species),
    map: createUpdateSchema(schema.maps),
    relativeType: createUpdateSchema(schema.relativeTypes),
    relative: createUpdateSchema(schema.relatives),
    contract: createUpdateSchema(schema.contracts),
    character: createUpdateSchema(schema.characters),
    characterAffiliation: createUpdateSchema(schema.characterAffiliations),
    affiliation: createUpdateSchema(schema.affiliations),
    characterOccupation: createUpdateSchema(schema.characterOccupations),
    occupation: createUpdateSchema(schema.occupations),
  },
};
