/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsNewRouteImport } from './routes/locations/new'
import { Route as LocationsLocationIdIndexRouteImport } from './routes/locations/$locationId/index'
import { Route as LocationsLocationIdEditRouteImport } from './routes/locations/$locationId/edit'
import { Route as ApiV1SplatRouteImport } from './routes/api.v1.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsNewRoute = LocationsNewRouteImport.update({
  id: '/locations/new',
  path: '/locations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsLocationIdIndexRoute =
  LocationsLocationIdIndexRouteImport.update({
    id: '/locations/$locationId/',
    path: '/locations/$locationId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocationsLocationIdEditRoute = LocationsLocationIdEditRouteImport.update({
  id: '/locations/$locationId/edit',
  path: '/locations/$locationId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/locations/new': typeof LocationsNewRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/locations/$locationId/edit': typeof LocationsLocationIdEditRoute
  '/locations/$locationId/': typeof LocationsLocationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/locations/new': typeof LocationsNewRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/locations/$locationId/edit': typeof LocationsLocationIdEditRoute
  '/locations/$locationId': typeof LocationsLocationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/locations/new': typeof LocationsNewRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/locations/$locationId/edit': typeof LocationsLocationIdEditRoute
  '/locations/$locationId/': typeof LocationsLocationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/locations/new'
    | '/api/v1/$'
    | '/locations/$locationId/edit'
    | '/locations/$locationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/locations/new'
    | '/api/v1/$'
    | '/locations/$locationId/edit'
    | '/locations/$locationId'
  id:
    | '__root__'
    | '/'
    | '/locations/new'
    | '/api/v1/$'
    | '/locations/$locationId/edit'
    | '/locations/$locationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocationsNewRoute: typeof LocationsNewRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  LocationsLocationIdEditRoute: typeof LocationsLocationIdEditRoute
  LocationsLocationIdIndexRoute: typeof LocationsLocationIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/new': {
      id: '/locations/new'
      path: '/locations/new'
      fullPath: '/locations/new'
      preLoaderRoute: typeof LocationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$locationId/': {
      id: '/locations/$locationId/'
      path: '/locations/$locationId'
      fullPath: '/locations/$locationId/'
      preLoaderRoute: typeof LocationsLocationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$locationId/edit': {
      id: '/locations/$locationId/edit'
      path: '/locations/$locationId/edit'
      fullPath: '/locations/$locationId/edit'
      preLoaderRoute: typeof LocationsLocationIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocationsNewRoute: LocationsNewRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  LocationsLocationIdEditRoute: LocationsLocationIdEditRoute,
  LocationsLocationIdIndexRoute: LocationsLocationIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
